// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: api/mapper.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MapperClient is the client API for Mapper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MapperClient interface {
	ChainsFromCoordinator(ctx context.Context, in *ChainsFromCoordinatorRequest, opts ...grpc.CallOption) (*ChainsFromCoordinatorResponse, error)
	CampaignsFromCoordinator(ctx context.Context, in *CampaignsFromCoordinatorRequest, opts ...grpc.CallOption) (*CampaignsFromCoordinatorResponse, error)
	ChainsFromValidatorAddress(ctx context.Context, in *ChainsFromValidatorAddressRequest, opts ...grpc.CallOption) (*ChainsFromValidatorAddressResponse, error)
}

type mapperClient struct {
	cc grpc.ClientConnInterface
}

func NewMapperClient(cc grpc.ClientConnInterface) MapperClient {
	return &mapperClient{cc}
}

func (c *mapperClient) ChainsFromCoordinator(ctx context.Context, in *ChainsFromCoordinatorRequest, opts ...grpc.CallOption) (*ChainsFromCoordinatorResponse, error) {
	out := new(ChainsFromCoordinatorResponse)
	err := c.cc.Invoke(ctx, "/ignite.backend.api.Mapper/ChainsFromCoordinator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapperClient) CampaignsFromCoordinator(ctx context.Context, in *CampaignsFromCoordinatorRequest, opts ...grpc.CallOption) (*CampaignsFromCoordinatorResponse, error) {
	out := new(CampaignsFromCoordinatorResponse)
	err := c.cc.Invoke(ctx, "/ignite.backend.api.Mapper/CampaignsFromCoordinator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapperClient) ChainsFromValidatorAddress(ctx context.Context, in *ChainsFromValidatorAddressRequest, opts ...grpc.CallOption) (*ChainsFromValidatorAddressResponse, error) {
	out := new(ChainsFromValidatorAddressResponse)
	err := c.cc.Invoke(ctx, "/ignite.backend.api.Mapper/ChainsFromValidatorAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapperServer is the server API for Mapper service.
// All implementations must embed UnimplementedMapperServer
// for forward compatibility
type MapperServer interface {
	ChainsFromCoordinator(context.Context, *ChainsFromCoordinatorRequest) (*ChainsFromCoordinatorResponse, error)
	CampaignsFromCoordinator(context.Context, *CampaignsFromCoordinatorRequest) (*CampaignsFromCoordinatorResponse, error)
	ChainsFromValidatorAddress(context.Context, *ChainsFromValidatorAddressRequest) (*ChainsFromValidatorAddressResponse, error)
	mustEmbedUnimplementedMapperServer()
}

// UnimplementedMapperServer must be embedded to have forward compatible implementations.
type UnimplementedMapperServer struct {
}

func (UnimplementedMapperServer) ChainsFromCoordinator(context.Context, *ChainsFromCoordinatorRequest) (*ChainsFromCoordinatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChainsFromCoordinator not implemented")
}
func (UnimplementedMapperServer) CampaignsFromCoordinator(context.Context, *CampaignsFromCoordinatorRequest) (*CampaignsFromCoordinatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CampaignsFromCoordinator not implemented")
}
func (UnimplementedMapperServer) ChainsFromValidatorAddress(context.Context, *ChainsFromValidatorAddressRequest) (*ChainsFromValidatorAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChainsFromValidatorAddress not implemented")
}
func (UnimplementedMapperServer) mustEmbedUnimplementedMapperServer() {}

// UnsafeMapperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapperServer will
// result in compilation errors.
type UnsafeMapperServer interface {
	mustEmbedUnimplementedMapperServer()
}

func RegisterMapperServer(s grpc.ServiceRegistrar, srv MapperServer) {
	s.RegisterService(&Mapper_ServiceDesc, srv)
}

func _Mapper_ChainsFromCoordinator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainsFromCoordinatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapperServer).ChainsFromCoordinator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ignite.backend.api.Mapper/ChainsFromCoordinator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapperServer).ChainsFromCoordinator(ctx, req.(*ChainsFromCoordinatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mapper_CampaignsFromCoordinator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignsFromCoordinatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapperServer).CampaignsFromCoordinator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ignite.backend.api.Mapper/CampaignsFromCoordinator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapperServer).CampaignsFromCoordinator(ctx, req.(*CampaignsFromCoordinatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mapper_ChainsFromValidatorAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainsFromValidatorAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapperServer).ChainsFromValidatorAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ignite.backend.api.Mapper/ChainsFromValidatorAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapperServer).ChainsFromValidatorAddress(ctx, req.(*ChainsFromValidatorAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mapper_ServiceDesc is the grpc.ServiceDesc for Mapper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mapper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ignite.backend.api.Mapper",
	HandlerType: (*MapperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChainsFromCoordinator",
			Handler:    _Mapper_ChainsFromCoordinator_Handler,
		},
		{
			MethodName: "CampaignsFromCoordinator",
			Handler:    _Mapper_CampaignsFromCoordinator_Handler,
		},
		{
			MethodName: "ChainsFromValidatorAddress",
			Handler:    _Mapper_ChainsFromValidatorAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/mapper.proto",
}
